"""
Django settings for transit_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import glob

# Configurar rutas específicas de Windows para GDAL/GEOS en GeoDjango.
# Se detecta automáticamente cualquier versión de PostgreSQL instalada
# (14, 16, 17, ...) y el nombre real de la DLL de GDAL, en vez de asumir
# una ruta y versión fijas, para que funcione igual en distintas máquinas.
if os.name == 'nt':
    for _pg_bin in sorted(glob.glob(r"C:\Program Files\PostgreSQL\*\bin"), reverse=True):
        _gdal_dlls = glob.glob(os.path.join(_pg_bin, 'libgdal-*.dll'))
        _geos_dll = os.path.join(_pg_bin, 'libgeos_c.dll')
        if _gdal_dlls and os.path.exists(_geos_dll):
            os.environ['PATH'] = _pg_bin + os.path.pathsep + os.environ['PATH']
            GDAL_LIBRARY_PATH = _gdal_dlls[0]
            GEOS_LIBRARY_PATH = _geos_dll
            break

# Permite forzar rutas manualmente vía variables de entorno si el
# autodetect anterior no encuentra las DLLs correctas.
if os.environ.get('GDAL_LIBRARY_PATH'):
    GDAL_LIBRARY_PATH = os.environ['GDAL_LIBRARY_PATH']
if os.environ.get('GEOS_LIBRARY_PATH'):
    GEOS_LIBRARY_PATH = os.environ['GEOS_LIBRARY_PATH']

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)izx#nibm!i$56z-nl*a%5o_0gcm)-w4f4_32xz%%xc3dp)qej'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts permitidos. En local queda vacío (Django con DEBUG acepta localhost).
# En el VPS se pasa ALLOWED_HOSTS por variable de entorno (ej. "*" o la IP)
# para que acepte peticiones dirigidas al host público. Ver docker-compose.yml.
ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',       # Requerido para GeoDjango (modelos espaciales)
    'corsheaders',              # Requerido para permitir peticiones desde React
    'transit_app',              # Nuestra app de transporte público
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Debe colocarse antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'transit_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transit_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',       # Motor de base de datos PostGIS
        'NAME': os.environ.get('DB_NAME', 'transporte_db'),       # Nombre de la base de datos
        'USER': os.environ.get('DB_USER', 'postgres'),            # Usuario por defecto de PostgreSQL
        'PASSWORD': os.environ.get('DB_PASSWORD', '84261704'),    # Contraseña de PostgreSQL
        'HOST': os.environ.get('DB_HOST', 'localhost'),           # 'db' cuando corre en Docker
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configuración de CORS para desarrollo local
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = ['http://localhost:5173', 'http://localhost:5174']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
