# Generated by Django 6.0.6 on 2026-06-17 22:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaMicro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
            ],
            options={
                'verbose_name': 'Línea de micro',
                'verbose_name_plural': 'Líneas de micro',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='stop',
            name='routes',
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sentido', models.CharField(choices=[('IDA', 'Ida'), ('VUELTA', 'Vuelta'), ('CIRCULAR', 'Circular')], default='CIRCULAR', max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='transit_app.lineamicro')),
            ],
            options={
                'ordering': ['linea__codigo', 'sentido'],
            },
        ),
        migrations.CreateModel(
            name='RutaParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_paradas', to='transit_app.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_paradas', to='transit_app.ruta')),
            ],
            options={
                'verbose_name': 'Parada de ruta',
                'verbose_name_plural': 'Paradas de ruta',
                'ordering': ['orden'],
                'unique_together': {('ruta', 'parada')},
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='paradas',
            field=models.ManyToManyField(related_name='rutas', through='transit_app.RutaParada', to='transit_app.parada'),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
